# Generated by Django 4.2.1 on 2023-05-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(default='lobby', max_length=255),
        ),
    ]
